# Generated by Django 4.1.7 on 2023-04-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
